version: "3.8"
services:
  react-roadmap-milestones-development:
    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: react-roadmap-milestones-development
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000