version: "3.8"
services:
  production-app:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: production-app
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000