name: Node.js CI
run-name: ${{ github.actor }} is executing GitHub Actions 🚀
on: [push, pull_request]
jobs:
  info:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    needs: info
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run test:ci
      - run: echo "🍏 This job's status is ${{ job.status }}."

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    needs: test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: echo "🍏 This job's status is ${{ job.status }}."
